name: RPi image

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ Drone3 ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker run --privileged --rm -v /dev:/dev -v $(pwd):/builder/repo -e TRAVIS_TAG="${{ github.event.release.tag_name }}" sfalexrog/img-tool:qemu-update
      - name: Rename and Compress image
        run: |
          cd images && sudo chmod -R 777 . && find . -type f -name 'clover*.img' -exec sed -i 's/clover/drone/' {} \; && zip -9 drone.zip drone* && ls -l . && unzip -l drone.zip
      - name: Upload image
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: images/drone.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}