name: Documentation

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ final-master ]
  release:
    types: [ created ]

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  docs:
    runs-on: ubuntu-22.04
    outputs:
      id: docs_outputs
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: { node-version: '10' }
      - name: Setup tools
        run: |
          sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
          sudo apt-get update && sudo apt-get install -y calibre msttcorefonts
          builder/assets/install_gitbook.sh
          npm install markdownlint-cli@0.28.1 -g # FIXME: https://github.com/DavidAnson/markdownlint/issues/435
          npm install svgexport -g
          gitbook -V
          markdownlint -V
      - name: Run markdownlint
        run: markdownlint docs
      - name: Check Assets
        run: |
          ./check_assets_size.py
          ./check_unused_assets.py

      - name: List Files in _book Directory
        run: |
          echo "Listing files in _book directory:"
          ls -l _book
